apiVersion: apps/v1
kind: Deployment
metadata:
  name: week4-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: week4-frontend
  template:
    metadata:
      labels:
        app: week4-frontend
    spec:
      containers:
        - name: frontend
          image: fivich/lemp-frontend:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080